In [1]:
from optimizer import Optimizer
from chromosome import Chromosome
from character import Character
from utils import get_item_set, elements
import os
from data import items, item_sets
from datetime import datetime
from analysis import construct_report_str
import json

In [25]:
# with open("reports/crit-omni-ranged/2026-09-05_15-44-02/config.json", "r") as file:
with open("workflows/report-sacri-tank_20260922-110152/run_training/config.json", "r") as file:
    config = json.load(file)
    # Convert all string keys into int
    config['character']['exo'] = {int(k): v for k, v in config['character']['exo'].items()}

In [26]:
import pandas as pd

dct = {}
for k,v in items.items():
    item_set = get_item_set(v,item_sets)
    dct[k] = {
        "name" : v["name"][config["optimizer"]["language"]],
        "set" : item_set["name"][config["optimizer"]["language"]] if item_set else None,
        "level" : v["level"],
        'ankama_id' : v['ankama_id']
    }
    dct[k].update({i:j for i,j in v['type'].items() if i not in dct[k]})
Items = pd.DataFrame.from_dict(dct, orient='index')

In [27]:
char = Character(**config["character"])
opt = Optimizer(char,
                 items,
                   item_sets,
                     **config["optimizer"])

Total items: 1796
Total item sets: 161
Total pools:
   16 with sizes [73, 104, 82, 82, 1, 82, 46, 93, 72, 453, 1, 1, 1, 1, 290, 290]
Total combinations: 10^22.69

In [28]:
Items[Items['name'].str.contains('allister', case=False)][['name', 'ankama_id']]

                                      name  ankama_id
22071  Bolsillito de merkasako de Allister      22071
13125                    Botas de Allister      13125
13055       Documento firmado por Allister      13055
30060                    Égida de Allister      30060
22263                 Bolso de Allisterina      22263
13123                   Corona de Allister      13123
13124                   Anillo de Allister      13124

In [36]:
Items.loc[
    [
			17581, # Collar de sota afortunada
			13124, # Anillo Allister
			17582, # Guantes de sota afortunada
			13125, # Botas Allister
			17583, # Capa sota
			20366, # Valentía de la Señorita Jhessica
			694, # Dofus Púrpura
			7115, # Dofus Marfil
			7754, # Dofus Ocre
			18043, # Dofus abisal
			7043, # Dofus de los hielos
			737, # Dofus esmeralda
			19263, # Escudo de Ilyzaelle
			24034, # Tintarela picuda
			11966, # Tejaluche
			13123, # Corona Allister
			]
]

,name,set,level,ankama_id,id,itemTypeId,superTypeId,categoryId
17581,Collar de sota afortunada,Set de la sota afortunada,200,17581,1,33,1,0
13124,Anillo de Allister,Set de Allister,197,13124,9,17,3,0
17582,Guantes de sota afortunada,Set de la sota afortunada,200,17582,9,17,3,0
13125,Botas de Allister,Set de Allister,191,13125,11,45,5,0
17583,Capa de sota afortunada,Set de la sota afortunada,200,17583,17,43,11,0
20366,Valentía de la Señorita Jhessica,NaN,200,20366,10,58,4,0
694,Dofus Púrpura,NaN,110,694,23,177,13,0
7115,Dofus Marfil,NaN,180,7115,23,177,13,0
7754,Dofus Ocre,NaN,160,7754,23,177,13,0
18043,Dofus abisal,NaN,180,18043,23,177,13,0
7043,Dofus de los hielos,NaN,180,7043,23,177,13,0
737,Dofus Esmeralda,NaN,100,737,23,177,13,0
19263,Escudo de Ilyzaelle,Set de Ilyzaelle,200,19263,82,87,7,0
24034,Tintarela picuda,NaN,200,24034,22,163,2,0
11966,Tejaluche,NaN,20,11966,18,1,12,0
13123,Corona de Allister,Set de Allister,196,13123,16,27,10,0

In [35]:
Items.loc[[7754, 7115, 18043, 694, 20366, 24034]]

,name,set,level,ankama_id,id,itemTypeId,superTypeId,categoryId
7754,Dofus Ocre,NaN,160,7754,23,177,13,0
7115,Dofus Marfil,NaN,180,7115,23,177,13,0
18043,Dofus abisal,NaN,180,18043,23,177,13,0
694,Dofus Púrpura,NaN,110,694,23,177,13,0
20366,Valentía de la Señorita Jhessica,NaN,200,20366,10,58,4,0
24034,Tintarela picuda,NaN,200,24034,22,163,2,0

In [31]:
# Sword set
chr = Chromosome(
                 [
			17581, # Collar de sota afortunada
			13124, # Anillo Allister
			17582, # Guantes de sota afortunada
			13125, # Botas Allister
			17583, # Capa sota
			20366, # Valentía de la Señorita Jhessica
			694, # Dofus Púrpura
			7115, # Dofus Marfil
			7754, # Dofus Ocre
			18043, # Dofus abisal
			7043, # Dofus de los hielos
			737, # Dofus esmeralda
			19263, # Escudo de Ilyzaelle
			24034, # Tintarela picuda
			11966, # Tejaluche
			13123, # Corona Allister
                 ],
                 opt)

report = construct_report_str(chr)
print(report)

	Fitness: 0.00045212747123502423
	Weapon damage: 842.82
		Weapon: Tintarela picuda
		AP Cost: 5
		Casts per turn: 1
	Spell damage:497.20000000000005
	Preferences:
		% crítico : -11.0
		% resistencia a la tierra : 14.0
		% resistencia al agua : 31.0
		% resistencia al aire : 31.0
		% resistencia al fuego : 14.0
		% resistencia neutral : 26.0
		PA : 12.0
		PM : 5.0
		huida : 69.0
		iniciativa : 1961.0
		placaje : 154.0
		potencia (daños generales) : 180.0
		vitalidad : 4650.0
	Characteristics:
		agilidad: 1291.0
	Items:
		Type	Description	Level	ID
		Amuleto	Collar de sota afortunada	200	17581
		Anillo	Anillo de Allister	197	13124
		Anillo	Guantes de sota afortunada	200	17582
		Bota	Botas de Allister	191	13125
		Capa	Capa de sota afortunada	200	17583
		Cinturón	Valentía de la Señorita Jhessica	200	20366
		Dofus	Dofus Púrpura	110	694
		Dofus	Dofus Esmeralda	100	737
		Dofus	Dofus de los hielos	180	7043
		Dofus	Dofus Marfil	180	7115
		Dofus	Dofus Ocre	160	7754
		Dofus	Dofus abisal	180	18043
		Escudo	Escudo de Ilyzaelle	200	19263
		Guadaña	Tintarela picuda	200	24034
		Mascota	Tejaluche	20	11966
		Sombrero	Corona de Allister	196	13123
	Penalized: True
		Penalized: 12 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 8 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 9 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 34 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 37 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 16 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 17 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 63 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 26 (lower) with offset 0.7615938734587377 and strength 0.01
		Penalized: 59 (lower) with offset 0.7615938734587377 and strength 0.01
	Chromosome: [
			17581, # Collar de sota afortunada
			13124, # Anillo de Allister
			17582, # Guantes de sota afortunada
			13125, # Botas de Allister
			17583, # Capa de sota afortunada
			20366, # Valentía de la Señorita Jhessica
			694, # Dofus Púrpura
			737, # Dofus Esmeralda
			7043, # Dofus de los hielos
			7115, # Dofus Marfil
			7754, # Dofus Ocre
			18043, # Dofus abisal
			19263, # Escudo de Ilyzaelle
			24034, # Tintarela picuda
			11966, # Tejaluche
			13123, # Corona de Allister
			]

In [28]:
chr.totals_summary().loc[62]

description    de daño de empuje
value                       29.0
Name: 62, dtype: object

In [27]:
chr.totals[62]

29.0

In [24]:
# Current
chr = Chromosome(
                 [
                    17683, # Hacha
                    21235, # Torkelonia
                    13642, # Noai
                    14161, 14162, 14169, # Charlatan
                    14092, 14093, 18718, # Kuko
                    13673, # Lokulto
                    739, 694, 7754, 737, 7043, 18043 # Dofus
                 ],
                 opt)

report = construct_report_str(chr)
print(report)

	Fitness: 0.0
	Weapon damage: 0
		Weapon: Hacha de Miauvizor
		AP Cost: 4
		Casts per turn: 1
	Spell damage:280.20000000000005
	Preferences:
		% crítico : 83.0
		% resistencia a la tierra : 18.0
		% resistencia al agua : 36.0
		% resistencia al aire : 42.0
		% resistencia al fuego : 16.0
		% resistencia neutral : 20.0
		PA : 12.0
		PM : 6.0
		huida : 89.0
		iniciativa : 2565.0
		placaje : 115.0
		potencia (daños generales) : 185.0
		vitalidad : 4200.0
	Characteristics:
		agilidad: 746.0
	Items:
		Type	Description	Level	ID
		Amuleto	Talismán Tira	200	14169
		Anillo	Anillo de Noai Aludem	197	13642
		Anillo	Anillo de kukoloide	200	14092
		Bota	Botas de kukoloide	200	14093
		Capa	Capa Ordiosera	200	14161
		Cinturón	Cinto Dovencible	200	14162
		Dofus	Dofus Púrpura	110	694
		Dofus	Dofus Esmeralda	100	737
		Dofus	Dofus Turquesa	160	739
		Dofus	Dofus de los hielos	180	7043
		Dofus	Dofus Ocre	160	7754
		Dofus	Dofus abisal	180	18043
		Escudo	Escudo de kukoloide	200	18718
		Hacha	Hacha de Miauvizor	200	17683
		Mascota	Lokulto	20	13673
		Sombrero	Cuerno de Torkelonia	200	21235
	Penalized: True
		Penalized: 12 (lower) with offset 1.0 and strength 0.01
		Penalized: 8 (lower) with offset 1.0 and strength 0.01
		Penalized: 9 (lower) with offset 1.0 and strength 0.01
		Penalized: 34 (lower) with offset 1.0 and strength 0.01
		Penalized: 37 (lower) with offset 1.0 and strength 0.01
		Penalized: 16 (lower) with offset 1.0 and strength 0.01
		Penalized: 17 (lower) with offset 1.0 and strength 0.01
		Penalized: 63 (lower) with offset 1.0 and strength 0.01
		Penalized: 26 (lower) with offset 1.0 and strength 0.01
		Penalized: 59 (lower) with offset 1.0 and strength 0.01
	Chromosome: [
			14169, # Talismán Tira
			13642, # Anillo de Noai Aludem
			14092, # Anillo de kukoloide
			14093, # Botas de kukoloide
			14161, # Capa Ordiosera
			14162, # Cinto Dovencible
			694, # Dofus Púrpura
			737, # Dofus Esmeralda
			739, # Dofus Turquesa
			7043, # Dofus de los hielos
			7754, # Dofus Ocre
			18043, # Dofus abisal
			18718, # Escudo de kukoloide
			17683, # Hacha de Miauvizor
			13673, # Lokulto
			21235, # Cuerno de Torkelonia
			]

In [ ]:
chr.get_item_contributions()[12]

2.0

In [ ]:
chr.get_set_contributions()[12]

2.0

In [ ]:
chr.character.stats[12]

8

In [ ]:
chr.penalized

True

In [ ]:
# Current
chr = Chromosome(
                 [
                    17578, 17579, 17580, 19984, 19983, 19985, 19986, 15190, 18700, 13673, 739, 13825, 18043, 7754, 7043, 694, 7115
                 ],
                 opt)

report = construct_report_str(chr)
print(report)

	Fitness: 0.0
	Weapon damage: 1140.6
		Weapon: Arco de vueloceronte
		AP Cost: 5
		Casts per turn: 1
	Spell damage:1360.8000000000002
	Preferences:
		% crítico : 82.0
		huida : 80.0
		placaje : 63.0
		potencia (daños generales) : 270.0
		% crítico : 82.0
		huida : 80.0
		placaje : 63.0
		potencia (daños generales) : 270.0
	Characteristics:
		agilidad: 636.0
		fuerza: 736.0
		suerte: 816.0
		inteligencia: 736.0
	Items:
		Type	Description	Level	ID
		Amuleto	Amuleto de vueloceronte	200	19984
		Anillo	Anillo de vueloceronte	200	19985
		Anillo	Brazalete de melenutrof	200	15190
		Arco	Arco de vueloceronte	200	19986
		Bota	Botas de Miauvizor	200	17578
		Capa	Capa de Miauvizor	200	17580
		Cinturón	Cinturón de vueloceronte	200	19983
		Dofus	Dofus Marfil	180	7115
		Dofus	Dofus de los hielos	180	7043
		Dofus	Dofus abisal	180	18043
		Dofus	Dofus Turquesa	160	739
		Dofus	Dofus Ocre	160	7754
		Dofus	Dofus Púrpura	110	694
		Escudo	Cuadrifolio	193	18700
		Mascota	Lokulto	20	13673
		Sombrero	Casco de Miauvizor	200	17579
		Trofeo	Potente mayor	150	13825
	Chromosome: [
			19984, # Amuleto de vueloceronte
			19985, # Anillo de vueloceronte
			15190, # Brazalete de melenutrof
			19986, # Arco de vueloceronte
			17578, # Botas de Miauvizor
			17580, # Capa de Miauvizor
			19983, # Cinturón de vueloceronte
			7115, # Dofus Marfil
			7043, # Dofus de los hielos
			18043, # Dofus abisal
			739, # Dofus Turquesa
			7754, # Dofus Ocre
			694, # Dofus Púrpura
			18700, # Cuadrifolio
			13673, # Lokulto
			17579, # Casco de Miauvizor
			13825, # Potente mayor
			]